# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6a69ea20a7add3d46e3377c2d9df2411ae41a7c9b59d5d7a5fac7e4be4d3f62e2023ce954f8c650c39cec23b7a8925a4eaa59ae8a3aa198a43c5c2a52497be8

test:
  secret_key_base: d822567d7a0e341e7acee2fcdc8d9b7207710746a971e0a9dd8af7db4e2bb4612ab76071fdfed6b969fe76b064f7a607103f407211b9094c7e9a68fc10848927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
